project:
  type: website
  output-dir: docs
  
website:
  title: "My Personal Website for STAT 37815"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: quartz
    mainfont: "'Roboto', sans-serif"
    theme: success
    # css: my-style.css
    # toc: true

