project:
  type: website
  output-dir: docs
  
website:
  title: "My Personal Website for STAT 37815"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: success
    mainfont: "'Roboto', sans-serif"
    
navbar:
tools:
- icon: github
href: https://github.com/mingxuan1130/mingxuan1130.github.io