project:
  type: website
  output-dir: docs
  
website:
  title: "My Personal Website for STAT 37815"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
    html:
      theme: flatly
      googlefonts: EB Garamond
      #Since "mainfont: "'EB Garamond'', sans-serif"" does not available 
      #through the local system, but I try "googlefonts: EB Garamond" 
      #and that works, so I will just use that
      
navbar:
tools:
- icon: github
href: https://github.com/mingxuan1130/mingxuan1130.github.io


    